version: '3.8'

services:
  ecliptix-opaque-linux:
    build:
      context: .
      dockerfile: Dockerfile.linux
    volumes:
      - ./dist:/workspace/dist
    container_name: ecliptix-opaque-linux-build
    profiles:
      - linux

  ecliptix-opaque-windows:
    build:
      context: .
      dockerfile: Dockerfile.windows
    volumes:
      - ./dist:C:/workspace/dist
    container_name: ecliptix-opaque-windows-build
    platform: windows/amd64
    profiles:
      - windows

networks:
  default:
    name: ecliptix-opaque-build