#pragma once

#define OPAQUE_AGENT_VERSION "1.0.0"
#define OPAQUE_RELAY_VERSION "1.0.0"
#define OPAQUE_AGENT_VERSION_MAJOR 1
#define OPAQUE_AGENT_VERSION_MINOR 0
#define OPAQUE_AGENT_VERSION_PATCH 0
#define OPAQUE_RELAY_VERSION_MAJOR 1
#define OPAQUE_RELAY_VERSION_MINOR 0
#define OPAQUE_RELAY_VERSION_PATCH 0
