#pragma once

#define OPAQUE_CLIENT_VERSION "1.0.0"
#define OPAQUE_SERVER_VERSION "1.0.0"
#define OPAQUE_CLIENT_VERSION_MAJOR 1
#define OPAQUE_CLIENT_VERSION_MINOR 0
#define OPAQUE_CLIENT_VERSION_PATCH 0
#define OPAQUE_SERVER_VERSION_MAJOR 1
#define OPAQUE_SERVER_VERSION_MINOR 0
#define OPAQUE_SERVER_VERSION_PATCH 0