name: Server Builds

on:
  push:
    branches: [ main, develop, 'claude/**' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Server - Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build server library (Docker)
        run: ./build.sh server-linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-linux
          path: dist/server/linux/
          if-no-files-found: error
          retention-days: 30

  build-windows:
    name: Build Server - Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build server library (Docker)
        run: ./build.sh server-windows
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-windows
          path: dist/server/windows/
          if-no-files-found: error
          retention-days: 30
